CREATE TABLE [dbo].[Medias]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[Name] NVARCHAR(255) NOT NULL,

	[CreatedBy] NVARCHAR(255) NULL,
	[Created] DATETIME DEFAULT(GETDATE()),
	[ModifiedBy] NVARCHAR(255) NULL,
	[Modified] DATETIME NULL,
)
