-- 비디오 테이블
CREATE TABLE [dbo].[Videos]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[Created] DATETIMEOFFSET(7) DEFAULT(SYSDATETIMEOFFSET() AT TIME ZONE 'KOREA STANDARD TIME'),
	[Title] NVARCHAR(MAX) NOT NULL,  -- 제목
	[Url] NVARCHAR(MAX) NULL,	-- URL
	[Name] NVARCHAR(MAX) NULL,	-- 이름
	[Company] NVARCHAR(255) NULL,	-- 회사
)
